export const doctors = [
    {active: true, rate: 4.9, reviews: 123, services: 24, name: "Лозовий Юрій Володимирович", img: "doctor-1", position: "Інфекціонист, Лікар-нарколог дільничий", location: "м. Луцьк, пр. Соборності 89", 'location-detail': "Луцька міська клінічна лікарня", price1: 100, price2: 300},
    {active: true, rate: 3.9, reviews: 240, services: 14, name: "Москаленко Дмитро  Миколайович", img: "doctor-2", position: "Інфекціонист, Лікар-нарколог дільничий", location: "м. Запоріжжя, пр. Соборності 19", 'location-detail': "Запорізька міська клінічна лікарня", price1: 200, price2: 500},
    {active: false, rate: 4.7, reviews: 97, services: 30, name: "Філатова Ірина  Миколаївна", img: "doctor-3", position: "Інфекціонист, Лікар-нарколог дільничий, дитячий невропотолог, Хірург", location: "м. Львів, пр. Свободи 23", 'location-detail': "Львівська міська клінічна лікарня", price1: 700, price2: 400},
    {active: true, rate: 5.0, reviews: 348, services: 52, name: "Шараєвська Вікторія  Володимирівна", img: "doctor-4", position: "Інфекціонист, Лікар-нарколог дільничий, Лікар-інфекціоніст дитячий, Лікар-хірург дитячий", location: "м. Київ, пр. Незалежності 70", 'location-detail': "Київська міська клінічна лікарня", price1: 600, price2: 100},
    {active: true, rate: 4.9, reviews: 123, services: 24, name: "Лозовий Юрій Володимирович", img: "doctor-1", position: "Інфекціонист, Лікар-нарколог дільничий", location: "м. Луцьк, пр. Соборності 89", 'location-detail': "Луцька міська клінічна лікарня", price1: 100, price2: 300},
    {active: true, rate: 3.9, reviews: 240, services: 14, name: "Москаленко Дмитро  Миколайович", img: "doctor-2", position: "Інфекціонист, Лікар-нарколог дільничий", location: "м. Запоріжжя, пр. Соборності 19", 'location-detail': "Запорізька міська клінічна лікарня", price1: 200, price2: 500},
    {active: false, rate: 4.7, reviews: 97, services: 30, name: "Філатова Ірина  Миколаївна", img: "doctor-3", position: "Інфекціонист, Лікар-нарколог дільничий, дитячий невропотолог, Хірург", location: "м. Львів, пр. Свободи 23", 'location-detail': "Львівська міська клінічна лікарня", price1: 700, price2: 400},
    {active: true, rate: 5.0, reviews: 348, services: 52, name: "Шараєвська Вікторія  Володимирівна", img: "doctor-4", position: "Інфекціонист, Лікар-нарколог дільничий, Лікар-інфекціоніст дитячий, Лікар-хірург дитячий", location: "м. Київ, пр. Незалежності 70", 'location-detail': "Київська міська клінічна лікарня", price1: 600, price2: 100},
]